# 2. Linear regression on house dataset
- Use this dataset on house price prediction in kaggle, 
- perform EDA on it and then predict the house prices using linear regression.
- You can drop the categorical features and the date columns. 
- Then try ElasticNetCV and RidgeCV on the same dataset. 
- Record the scores in a dataframe with the columns mae, mse, rmse so you can compare the models.

### EDA

In [547]:
import pandas as pd

df = pd.read_csv("../../data/data.csv")#) # make date column index and parse dates

df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [548]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [549]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [550]:
df = df.drop(["date", "street", "city", "statezip", "country"], axis="columns")
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

In [551]:
df.shape

(4600, 13)

In [552]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

### divide X, y

In [553]:
X, y = df.drop("price", axis = "columns"), df["price"]
X.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

In [554]:
y.head()

0     313000.0
1    2384000.0
2     342000.0
3     420000.0
4     550000.0
Name: price, dtype: float64

## Linear regression

In [555]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

X_train.shape, y_train.shape

((3082, 12), (3082,))

In [556]:
from sklearn.preprocessing import MinMaxScaler

scaler_MinMax = MinMaxScaler()
scaler_MinMax.fit(X_train)
scaled_X_train = scaler_MinMax.transform(X_train) 
scaled_X_test = scaler_MinMax.transform(X_test) 

scaled_X_train.min(), scaled_X_train.max(), scaled_X_test.min(), scaled_X_test.max()

(np.float64(0.0),
 np.float64(1.0),
 np.float64(-6.148033467658553e-05),
 np.float64(1.3619441571871767))

In [557]:
from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear

LinearRegression()

In [558]:
model_linear.fit(scaled_X_train, y_train)
model_linear.coef_

array([-632961.81002926,  183976.01614267, 1331571.73914542,
       -530140.69848596,  177191.62069176,  399702.99214839,
        168311.44859383,  121549.92982669, 1215092.06710175,
        742913.77680659, -296813.44004883,   11894.27813395])

In [559]:
model_linear.intercept_

np.float64(265073.54098144686)

## Linear - prediction

In [560]:
test_sample_1_features = scaled_X_test[0].reshape(1, -1)
test_sample_1_target = y_test.values[0]
test_sample_1_features, test_sample_1_target

(array([[3.33333333e-01, 3.70370370e-01, 1.12719752e-01, 8.46751882e-04,
         4.00000000e-01, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
         1.05882353e-01, 5.80912863e-02, 9.38596491e-01, 0.00000000e+00]]),
 np.float64(544000.0))

In [561]:
test_sample_1_features.shape

(1, 12)

In [562]:
model_linear.predict(test_sample_1_features)

array([296748.2583545])

In [563]:
test_sample_1_target

np.float64(544000.0)

In [564]:
y_pred = model_linear.predict(scaled_X_test)
y_pred.shape

(1518,)

In [565]:
y_pred[:5]

array([ 296748.2583545 ,  318512.5986427 , 1067958.25109663,
        551073.20614371,  371726.21302356])

In [566]:
y_test[:5].values

array([ 544000.,       0., 1712500.,  365000.,  275000.])

In [567]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"{mae = :.2f}")
print(f"{mse = :.2f}")
print(f"{rmse = :.2f}")

mae = 191902.16
mse = 621380924636.52
rmse = 788277.19

In [568]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

### polynominal feature

In [569]:
from sklearn.preprocessing import PolynomialFeatures

model_poly = PolynomialFeatures(3, include_bias=False)
poly_features = model_poly.fit_transform(X)
poly_features

array([[3.00000000e+00, 1.50000000e+00, 1.34000000e+03, ...,
        7.66316012e+09, 7.85914888e+09, 8.06015012e+09],
       [5.00000000e+00, 2.50000000e+00, 3.65000000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.00000000e+00, 2.00000000e+00, 1.93000000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [3.00000000e+00, 2.50000000e+00, 3.01000000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.00000000e+00, 2.00000000e+00, 2.09000000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.00000000e+00, 2.50000000e+00, 1.49000000e+03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],
      shape=(4600, 454))

### train|test split

In [570]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    poly_features, y, test_size=0.33, random_state=42)

X_train.shape, y_train.shape

((3082, 454), (3082,))

### scale data

In [571]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train) 
scaled_X_test = scaler.transform(X_test) 

scaled_X_train.min(), scaled_X_train.max(), scaled_X_test.min(), scaled_X_test.max()

(np.float64(0.0),
 np.float64(1.0000000000000002),
 np.float64(-0.007516009379328864),
 np.float64(7.784073102012656))

### ElasticNetCV and RidgeCV on the same dataset

In [572]:
from sklearn.linear_model import ElasticNet, RidgeCV

elasticCV_model = ElasticNet()
elasticCV_model

ElasticNet()

In [573]:
riverCV_model = RidgeCV()
riverCV_model

RidgeCV()