# KNN - K nearest neighbours

In [81]:
from sklearn.datasets import load_wine
import pandas as pd

wine = load_wine() # en dict
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [82]:
pd.DataFrame(wine["data"])

        0     1     2     3      4   ...    8      9     10    11      12
0    14.23  1.71  2.43  15.6  127.0  ...  2.29   5.64  1.04  3.92  1065.0
1    13.20  1.78  2.14  11.2  100.0  ...  1.28   4.38  1.05  3.40  1050.0
2    13.16  2.36  2.67  18.6  101.0  ...  2.81   5.68  1.03  3.17  1185.0
3    14.37  1.95  2.50  16.8  113.0  ...  2.18   7.80  0.86  3.45  1480.0
4    13.24  2.59  2.87  21.0  118.0  ...  1.82   4.32  1.04  2.93   735.0
..     ...   ...   ...   ...    ...  ...   ...    ...   ...   ...     ...
173  13.71  5.65  2.45  20.5   95.0  ...  1.06   7.70  0.64  1.74   740.0
174  13.40  3.91  2.48  23.0  102.0  ...  1.41   7.30  0.70  1.56   750.0
175  13.27  4.28  2.26  20.0  120.0  ...  1.35  10.20  0.59  1.56   835.0
176  13.17  2.59  2.37  20.0  120.0  ...  1.46   9.30  0.60  1.62   840.0
177  14.13  4.10  2.74  24.5   96.0  ...  1.35   9.20  0.61  1.60   560.0

[178 rows x 13 columns]

In [83]:
wine["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [84]:
len(wine["feature_names"])

13

In [85]:
wine["target"].shape, wine["data"].shape

((178,), (178, 13))

In [86]:
df = pd.DataFrame(wine["data"], columns=wine["feature_names"])
df.head()

   alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [87]:
df_wine_classes = pd.DataFrame(wine["target"], columns=["wine_class"])
df_wine_classes.head()

   wine_class
0           0
1           0
2           0
3           0
4           0

In [91]:
# concat df with new column wine_class 
df_with_target = pd.concat([df, df_wine_classes], axis=1)
df_with_target.head()

   alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  wine_class
0    14.23        1.71  2.43  ...                          3.92   1065.0           0
1    13.20        1.78  2.14  ...                          3.40   1050.0           0
2    13.16        2.36  2.67  ...                          3.17   1185.0           0
3    14.37        1.95  2.50  ...                          3.45   1480.0           0
4    13.24        2.59  2.87  ...                          2.93    735.0           0

[5 rows x 14 columns]

In [92]:
df_with_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  wine_class                    178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

### Dataframe with features and target

In [89]:
# print(f"{df.shape[0]} samples")
# print(f"{df.shape[1] - 1} features")
# print("sales column is our label/target")

# tuple unpacking
# X - design matrix / feature matrix / features / independent variables
# y - target variable / laberl / dependent variable
X, y = df.drop(target, axis = "columns"), df["target_names"]
X.head()

KeyError: '[0] not found in axis'